# Generated by Django 5.2.17 on 2026-09-01 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('feed_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('external_id', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(choices=[('injury', 'Injury'), ('suspension', 'Suspension'), ('lineup', 'Line-up'), ('transfer', 'Transfer'), ('training', 'Training'), ('performance', 'Performance'), ('coach_statement', 'Coach statement'), ('general', 'General news')], default='general', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('retrieved_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_items', to='players.team')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to='players.player')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.newssource')),
            ],
            options={
                'verbose_name_plural': 'player news',
                'ordering': ['-published_at', '-retrieved_at'],
                'indexes': [models.Index(fields=['player', '-published_at'], name='news_player_player__b18e5f_idx'), models.Index(fields=['source', 'title', 'published_at'], name='news_player_source__d8a618_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('source', 'external_id'), name='unique_news_external_id_per_source')],
            },
        ),
    ]
