# Generated by Django 5.2.17 on 2026-09-01 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSeasonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FWD', 'Forward')], max_length=3)),
                ('appearances', models.PositiveSmallIntegerField(default=0)),
                ('starts', models.PositiveSmallIntegerField(default=0)),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('goals', models.PositiveSmallIntegerField(default=0)),
                ('assists', models.PositiveSmallIntegerField(default=0)),
                ('yellow_cards', models.PositiveSmallIntegerField(default=0)),
                ('red_cards', models.PositiveSmallIntegerField(default=0)),
                ('own_goals', models.PositiveSmallIntegerField(default=0)),
                ('clean_sheets', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('matches_missed', models.PositiveSmallIntegerField(default=0)),
                ('fantasy_points', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('fantasy_average', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='players.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='seasons.season')),
            ],
            options={
                'verbose_name_plural': 'player season stats',
                'indexes': [models.Index(fields=['season', 'position'], name='stats_playe_season__5d042d_idx')],
                'constraints': [models.UniqueConstraint(fields=('player', 'season'), name='unique_stats_per_player_season')],
            },
        ),
        migrations.CreateModel(
            name='PlayerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('starting', 'Starting'), ('bench', 'Bench'), ('injured', 'Injured'), ('suspended', 'Suspended'), ('doubtful', 'Doubtful'), ('unavailable', 'Unavailable'), ('returning', 'Returning from injury'), ('unknown', 'Unknown')], max_length=15)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('is_confirmed', models.BooleanField(default=True, help_text='False if this is a prediction/rumor rather than confirmed information.')),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='players.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_statuses', to='seasons.season')),
            ],
            options={
                'verbose_name_plural': 'player statuses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['player', 'season', '-created_at'], name='stats_playe_player__a15002_idx')],
            },
        ),
    ]
