# Generated by Django 5.2.17 on 2026-09-01 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPriceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_type', models.CharField(choices=[('observed', 'Actual observed price'), ('estimated', 'Estimated price'), ('user_entered', 'User-entered price'), ('system_valuation', 'System-generated valuation')], max_length=20)),
                ('source', models.CharField(blank=True, help_text='Where this price observation came from, e.g. an aggregator name.', max_length=100)),
                ('is_anonymized', models.BooleanField(default=True, help_text='True unless the contributing manager explicitly consented to attribution.')),
                ('observed_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_prices', to='players.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_prices', to='seasons.season')),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['player', 'season', 'price_type'], name='market_mark_player__93efa0_idx')],
            },
        ),
    ]
