# Generated by Django 5.2.17 on 2026-09-01 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
        ('players', '0001_initial'),
        ('seasons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='draft', max_length=15)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='leagues.league')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionNomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('sold', 'Sold'), ('unsold', 'Unsold'), ('withdrawn', 'Withdrawn')], default='in_progress', max_length=15)),
                ('current_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('nominated_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='auction.auction')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominations', to='players.player')),
                ('winning_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_nominations', to='leagues.fantasymanager')),
            ],
            options={
                'ordering': ['-nominated_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('is_correction', models.BooleanField(default=False)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='auction.auction')),
                ('corrects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='auction.auctiontransaction')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='leagues.league')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='leagues.fantasymanager')),
                ('nomination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='auction.auctionnomination')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auction_transactions', to='players.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='seasons.season')),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='leagues.fantasymanager')),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auction.auctionnomination')),
            ],
            options={
                'ordering': ['placed_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_auction', 'Currently being auctioned'), ('purchased', 'Purchased'), ('unsold', 'Unsold'), ('unavailable', 'Unavailable'), ('withdrawn', 'Withdrawn')], default='available', max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_availabilities', to='leagues.league')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='players.player')),
            ],
            options={
                'verbose_name_plural': 'player availabilities',
            },
        ),
        migrations.AddIndex(
            model_name='auctionnomination',
            index=models.Index(fields=['auction', 'status'], name='auction_auc_auction_d64799_idx'),
        ),
        migrations.AddIndex(
            model_name='auctiontransaction',
            index=models.Index(fields=['league', 'manager'], name='auction_auc_league__be68e5_idx'),
        ),
        migrations.AddIndex(
            model_name='auctiontransaction',
            index=models.Index(fields=['league', 'player'], name='auction_auc_league__1fd9eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='auctiontransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('is_correction', False)), fields=('league', 'player'), name='unique_original_purchase_per_league_player'),
        ),
        migrations.AddIndex(
            model_name='playeravailability',
            index=models.Index(fields=['league', 'status'], name='auction_pla_league__60ff42_idx'),
        ),
        migrations.AddConstraint(
            model_name='playeravailability',
            constraint=models.UniqueConstraint(fields=('league', 'player'), name='unique_availability_per_league_player'),
        ),
    ]
