# Generated by Django 5.2.17 on 2026-09-01 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
        ('players', '0001_initial'),
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('engine_version', models.CharField(help_text='Identifies which valuation algorithm produced this result.', max_length=50)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='leagues.league')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='players.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='seasons.season')),
            ],
        ),
        migrations.CreateModel(
            name='ValuationComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('valuation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='valuations.playervaluation')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='playervaluation',
            index=models.Index(fields=['league', 'season'], name='valuations__league__72c0a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='playervaluation',
            constraint=models.UniqueConstraint(fields=('player', 'league', 'season'), name='unique_valuation_per_player_league_season'),
        ),
    ]
