# Generated by Django 5.2.17 on 2026-09-01 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seasons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('num_managers', models.PositiveSmallIntegerField(default=8)),
                ('initial_credits', models.PositiveIntegerField(default=500)),
                ('squad_size', models.PositiveSmallIntegerField(default=25)),
                ('slots_goalkeepers', models.PositiveSmallIntegerField(default=3)),
                ('slots_defenders', models.PositiveSmallIntegerField(default=8)),
                ('slots_midfielders', models.PositiveSmallIntegerField(default=8)),
                ('slots_forwards', models.PositiveSmallIntegerField(default=6)),
                ('min_bid', models.PositiveIntegerField(default=1)),
                ('max_bid', models.PositiveIntegerField(blank=True, null=True)),
                ('allow_overspend', models.BooleanField(default=False, help_text='If disabled (default), a manager cannot bid more credits than they have left.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_leagues', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leagues', to='seasons.season')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FantasyManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fantasy_manager_profiles', to=settings.AUTH_USER_MODEL)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='leagues.league')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeagueMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('viewer', 'Viewer')], default='viewer', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='leagues.league')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='league',
            constraint=models.UniqueConstraint(fields=('owner', 'name', 'season'), name='unique_league_per_owner_season'),
        ),
        migrations.AddConstraint(
            model_name='fantasymanager',
            constraint=models.UniqueConstraint(fields=('league', 'name'), name='unique_manager_name_per_league'),
        ),
        migrations.AddConstraint(
            model_name='leaguemembership',
            constraint=models.UniqueConstraint(fields=('league', 'user'), name='unique_membership_per_user_league'),
        ),
    ]
