# Generated by Django 5.2.17 on 2026-09-01 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('display_name', models.CharField(help_text='Name shown in the UI, e.g. in search results and the auction board.', max_length=150)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FWD', 'Forward')], max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=20)),
                ('external_id', models.CharField(blank=True, help_text='Stable identifier from an external data provider, if any.', max_length=100, null=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerIdentityMatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_input', models.JSONField(help_text='Raw provider payload fragment used for matching (name, club, ids, ...).')),
                ('match_method', models.CharField(choices=[('external_id', 'Stable external ID'), ('provider_id', 'Provider-specific identifier'), ('club_and_name', 'Club + player information'), ('name', 'Name matching'), ('fuzzy', 'Fuzzy matching'), ('manual', 'Manual resolution')], max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('matched_automatically', models.BooleanField(default=True)),
                ('is_ambiguous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_match_logs', to='players.player')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_players', to='players.team'),
        ),
        migrations.AddField(
            model_name='player',
            name='previous_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='former_players', to='players.team'),
        ),
        migrations.CreateModel(
            name='PlayerAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=150)),
                ('alias_type', models.CharField(choices=[('full_name', 'Full name'), ('short_name', 'Short name'), ('nickname', 'Nickname'), ('provider_name', 'Provider-specific name'), ('accented', 'Name with accents'), ('unaccented', 'Name without accents'), ('historical', 'Historical name')], max_length=20)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='players.player')),
            ],
            options={
                'indexes': [models.Index(fields=['alias'], name='players_pla_alias_c2e58f_idx')],
                'constraints': [models.UniqueConstraint(fields=('alias', 'alias_type', 'player'), name='unique_alias_per_player_and_type')],
            },
        ),
        migrations.CreateModel(
            name='PlayerExternalId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('external_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_ids', to='players.player')),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'external_id'], name='players_pla_provide_4346c6_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_id'), name='unique_provider_external_id')],
            },
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['display_name'], name='players_pla_display_584b62_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['full_name'], name='players_pla_full_na_c03349_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['position'], name='players_pla_positio_2502c1_idx'),
        ),
    ]
